[package]
name = "tool-chaining"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "*", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }